config/routes.rb
VisionBoard20::Application.routes.draw do

  # root to: "high_voltage/pages#show", id: 'index'
  unauthenticated do
    root to: "high_voltage/pages#show", id: 'index'
  end

  devise_for :users

  authenticated :user do
    root to: "Slideshows#index"
  end

  authenticate do
    resources :soundtracks
    resources :playlists
    resources :photo_arrays
    resources :photo_libraries
    resources :slideshows
    resources :songs
    resources :photographs
  end
  resources :usersend
end

app/models/photo_array.rb
class PhotoArray < ActiveRecord::Base
  attr_accessible :photograph_id, :slideshow_id

  belongs_to :photograph
  belongs_to :slideshow 

end

app/controllers/photo_arrays_controller.rb
class PhotoArraysController < ApplicationController
  # GET /photo_arrays
  # GET /photo_arrays.json
  def index
    @photo_arrays = PhotoArray.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photo_arrays }
    end
  end

  # GET /photo_arrays/1
  # GET /photo_arrays/1.json
  def show
    @photo_array = PhotoArray.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo_array }
    end
  end

  # GET /photo_arrays/new
  # GET /photo_arrays/new.json
  def new
    @photo_array = PhotoArray.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo_array }
    end
  end

  # GET /photo_arrays/1/edit
  def edit
    @photo_array = PhotoArray.find(params[:id])
  end

  # POST /photo_arrays
  # POST /photo_arrays.json
  def create
    @photo_array = PhotoArray.new(params[:photo_array])

    respond_to do |format|
      if @photo_array.save
        format.html { redirect_to @photo_array, notice: 'Photo array was successfully created.' }
        format.json { render json: @photo_array, status: :created, location: @photo_array }
      else
        format.html { render action: "new" }
        format.json { render json: @photo_array.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photo_arrays/1
  # PUT /photo_arrays/1.json
  def update
    @photo_array = PhotoArray.find(params[:id])

    respond_to do |format|
      if @photo_array.update_attributes(params[:photo_array])
        format.html { redirect_to @photo_array, notice: 'Photo array was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo_array.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photo_arrays/1
  # DELETE /photo_arrays/1.json
  def destroy
    @photo_array = PhotoArray.find(params[:id])
    @photo_array.destroy

    respond_to do |format|
      format.html { redirect_to photo_arrays_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/photo_arrays_helper.rb
module PhotoArraysHelper
end

app/views/photo_arrays/_form.html.erb
<%= form_for(@photo_array) do |f| %>
  <% if @photo_array.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo_array.errors.count, "error") %> prohibited this photo_array from being saved:</h2>

      <ul>
      <% @photo_array.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :photograph_id %><br />
    <%= f.number_field :photograph_id %>
  </div>
  <div class="field">
    <%= f.label :slideshow_id %><br />
    <%= f.number_field :slideshow_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photo_arrays/edit.html.erb
<h1>Editing photo_array</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo_array %> |
<%= link_to 'Back', photo_arrays_path %>

app/views/photo_arrays/index.html.erb
<h1>Listing photo_arrays</h1>

<table>
  <tr>
    <th>Photograph</th>
    <th>Slideshow</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photo_arrays.each do |photo_array| %>
  <tr>
    <td><%= photo_array.photograph_id %></td>
    <td><%= photo_array.slideshow_id %></td>
    <td><%= link_to 'Show', photo_array %></td>
    <td><%= link_to 'Edit', edit_photo_array_path(photo_array) %></td>
    <td><%= link_to 'Destroy', photo_array, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo array', new_photo_array_path %>

app/views/photo_arrays/new.html.erb
<h1>New photo_array</h1>

<%= render 'form' %>

<%= link_to 'Back', photo_arrays_path %>

app/views/photo_arrays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Photograph:</b>
  <%= @photo_array.photograph_id %>
</p>

<p>
  <b>Slideshow:</b>
  <%= @photo_array.slideshow_id %>
</p>


<%= link_to 'Edit', edit_photo_array_path(@photo_array) %> |
<%= link_to 'Back', photo_arrays_path %>