config/routes.rb
VisionBoard20::Application.routes.draw do

  # root to: "high_voltage/pages#show", id: 'index'
  unauthenticated do
    root to: "high_voltage/pages#show", id: 'index'
  end

  devise_for :users

  authenticated :user do
    root to: "Slideshows#index"
  end

  authenticate do
    resources :soundtracks
    resources :playlists
    resources :photo_arrays
    resources :photo_libraries
    resources :slideshows
    resources :songs
    resources :photographs
  end
  resources :usersend
end

app/models/photograph.rb
class Photograph < ActiveRecord::Base
  attr_accessible :comment, :image, :photo_caption, :tags, :remote_image_url

  has_many :photo_libraries
  has_many :users, :through => :photo_libraries

  has_many :photo_arrays
  has_many :slideshows, :through => :photo_arrays

  mount_uploader :image, ImageUploader

end

app/controllers/photographs_controller.rb
class PhotographsController < ApplicationController
  # GET /photographs
  # GET /photographs.json
  def index
    @photographs = Photograph.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photographs }
    end
  end

  # GET /photographs/1
  # GET /photographs/1.json
  def show
    @photograph = Photograph.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photograph }
    end
  end

  # GET /photographs/new
  # GET /photographs/new.json
  def new
    @photograph = Photograph.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photograph }
    end
  end

  # GET /photographs/1/edit
  def edit
    @photograph = Photograph.find(params[:id])
  end

  # POST /photographs
  # POST /photographs.json
  def create
    @photograph = Photograph.new(params[:photograph])

    respond_to do |format|
      if @photograph.save
        format.html { redirect_to @photograph, notice: 'Photograph was successfully created.' }
        format.json { render json: @photograph, status: :created, location: @photograph }
      else
        format.html { render action: "new" }
        format.json { render json: @photograph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photographs/1
  # PUT /photographs/1.json
  def update
    @photograph = Photograph.find(params[:id])

    respond_to do |format|
      if @photograph.update_attributes(params[:photograph])
        format.html { redirect_to @photograph, notice: 'Photograph was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photograph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photographs/1
  # DELETE /photographs/1.json
  def destroy
    @photograph = Photograph.find(params[:id])
    @photograph.destroy

    respond_to do |format|
      format.html { redirect_to photographs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/photographs_helper.rb
module PhotographsHelper
end

app/views/photographs/_form.html.erb
<%= form_for @photograph, :html => {:multipart => true} do |f| %>
  <% if @photograph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photograph.errors.count, "error") %> prohibited this photograph from being saved:</h2>

      <ul>
      <% @photograph.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :remote_image_url, "or Image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </div>
  <div class="field">
    <%= f.label :photo_caption %><br />
    <%= f.text_field :photo_caption %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_field :tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photographs/edit.html.erb
<h1>Editing photograph</h1>

<%= render 'form' %>

<%= link_to 'Show', @photograph %> |
<%= link_to 'Back', photographs_path %>

app/views/photographs/index.html.erb
<h1>Listing photographs</h1>

<table>
  <tr>
    <th>Image</th>
    <th>Photo caption</th>
    <th>Comment</th>
    <th>Tags</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photographs.each do |photograph| %>
  <tr>
    <td><%= image_tag photograph.image, width: 200 %></td>
    <td><%= photograph.photo_caption %></td>
    <td><%= photograph.comment %></td>
    <td><%= photograph.tags %></td>
    <td><%= link_to 'Show', photograph %></td>
    <td><%= link_to 'Edit', edit_photograph_path(photograph) %></td>
    <td><%= link_to 'Destroy', photograph, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photograph', new_photograph_path %>

app/views/photographs/new.html.erb
<h1>New photograph</h1>

<%= render 'form' %>

<%= link_to 'Back', photographs_path %>

app/views/photographs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= image_tag @photograph.image, width: 300 %>
</p>

<p>
  <b>Photo caption:</b>
  <%= @photograph.photo_caption %>
</p>

<p>
  <b>Comment:</b>
  <%= @photograph.comment %>
</p>

<p>
  <b>Tags:</b>
  <%= @photograph.tags %>
</p>


<%= link_to 'Edit', edit_photograph_path(@photograph) %> |
<%= link_to 'Back', photographs_path %>