config/routes.rb
VisionBoard20::Application.routes.draw do

  # root to: "high_voltage/pages#show", id: 'index'
  unauthenticated do
    root to: "high_voltage/pages#show", id: 'index'
  end

  devise_for :users

  authenticated :user do
    root to: "Slideshows#index"
  end

  authenticate do
    resources :soundtracks
    resources :playlists
    resources :photo_arrays
    resources :photo_libraries
    resources :slideshows
    resources :songs
    resources :photographs
  end
  resources :usersend
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  attr_accessible :song_id, :user_id

  belongs_to :user
  belongs_to :song 

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @playlists }
    end
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/new
  # GET /playlists/new.json
  def new
    @playlist = Playlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/1/edit
  def edit
    @playlist = Playlist.find(params[:id])
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(params[:playlist])

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render json: @playlist, status: :created, location: @playlist }
      else
        format.html { render action: "new" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /playlists/1
  # PUT /playlists/1.json
  def update
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      if @playlist.update_attributes(params[:playlist])
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :song_id %><br />
    <%= f.number_field :song_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<h1>Listing playlists</h1>

<table>
  <tr>
    <th>User</th>
    <th>Song</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @playlists.each do |playlist| %>
  <tr>
    <td><%= playlist.user_id %></td>
    <td><%= playlist.song_id %></td>
    <td><%= link_to 'Show', playlist %></td>
    <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
    <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Playlist', new_playlist_path %>

app/views/playlists/new.html.erb
<h1>New playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @playlist.user_id %>
</p>

<p>
  <b>Song:</b>
  <%= @playlist.song_id %>
</p>


<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>